// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(task_status_id))]
pub struct TaskStatuse {
    pub task_status_id: i32,
    pub status_name: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(task_id))]
pub struct Task {
    pub task_id: i32,
    pub task_name: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(user_id, task_id))]
pub struct UserTask {
    pub user_id: i32,
    pub task_id: i32,
    pub task_status_id: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(user_id))]
pub struct User {
    pub user_id: i32,
    pub name: String,
    pub email: String,
    pub active: bool,
}

